duck_tracker/apps/ducks/urls.py
from django.urls import path

from .views import FlockCreateUpdateView
from .views import FlockDeleteView
from .views import FlockDetailView
from .views import FlockListView
from .views import FlockStatsExportView
from .views import FlockStatsImportView
from .views import StatsCreateUpdateView
from .views import StatsImportTemplateView
from .views import FlockIncomeCalculatorView

app_name = "ducks"
urlpatterns = [
    path("flocks", FlockListView.as_view(), name="flock-list"),
    path("flock/<int:pk>/", FlockDetailView.as_view(), name="flock-detail"),
    path("flock/add/", FlockCreateUpdateView.as_view(), name="flock-add"),
    path("flock/<int:pk>/edit/", FlockCreateUpdateView.as_view(), name="flock-edit"),
    path("delete/<int:pk>/", FlockDeleteView.as_view(), name="flock-delete"),
    path("stats/add/", StatsCreateUpdateView.as_view(), name="stats-add"),
    path("stats/<int:pk>/edit/", StatsCreateUpdateView.as_view(), name="stats-edit"),
    path(
        "flocks/<int:pk>/export/",
        FlockStatsExportView.as_view(),
        name="flock-export",
    ),
    path(
        "flocks/<int:pk>/import/",
        FlockStatsImportView.as_view(),
        name="flock-import",
    ),
    path(
        "flocks/<int:pk>/import/template/",
        StatsImportTemplateView.as_view(),
        name="stats-import-template",
    ),
    path(
        "income-calculator/",
        FlockIncomeCalculatorView.as_view(),
        name="income-calculator",
    ),
]

duck_tracker/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("duck_tracker.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ducks/", include("apps.ducks.urls", namespace="ducks")),
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token, name="obtain_auth_token"),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

duck_tracker/duck_tracker/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

duck_tracker/duck_tracker/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Duck Tracker.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

duck_tracker/duck_tracker/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.AdminUserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

duck_tracker/duck_tracker/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from duck_tracker.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

duck_tracker/duck_tracker/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from duck_tracker.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

duck_tracker/duck_tracker/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

duck_tracker/duck_tracker/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        test
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Behold My Awesome Project!" />
    <meta name="author" content="simpleciel" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      <!-- Bootstrap Icons -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
            rel="stylesheet" />
      <link href="{% static 'css/project.min.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      <script defer src="{% static 'js/vendors.min.js' %}"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body class="{% block bodyclass %}{% endblock bodyclass %}">
    {% block body %}
      <div class="mb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
          <div class="container">
            <!-- Brand -->
            <a class="navbar-brand fw-bold text-primary" href="{% url 'home' %}">🦆 DuckTracker</a>
            <!-- Toggler -->
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Nav Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Left side -->
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active fw-semibold{% endif %}"
                     href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active fw-semibold{% endif %}"
                     href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if 'flock' in request.path %}active fw-semibold{% endif %}"
                     href="{% url 'ducks:flock-list' %}">Flocks</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if 'income' in request.path %}active fw-semibold{% endif %}"
                     href="{% url 'ducks:income-calculator' %}">Income Calculator</a>
                </li>
              </ul>
              <!-- Right side -->
              <ul class="navbar-nav ms-auto align-items-md-center gap-md-2">
                {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'users:detail' request.user.username %}">
                      <i class="bi bi-person-circle"></i> My Profile
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="btn btn-outline-danger btn-sm"
                       href="{% url 'account_logout' %}">Sign Out</a>
                  </li>
                {% else %}
                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                    <li class="nav-item">
                      <a class="btn btn-outline-primary btn-sm"
                         href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="btn btn-primary btn-sm" href="{% url 'account_login' %}">Sign In</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <main class="container py-4">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        {% block main %}
          {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
        {% endblock main %}
      </main>
    {% endblock body %}
    <!-- /container -->
    {% block footer %}
      <footer class="bg-white border-top shadow-sm mt-5">
        <div class="container py-4">
          <div class="row gy-3 align-items-center">
            <!-- Brand + description -->
            <div class="col-md-6 text-center text-md-start">
              <a href="{% url 'home' %}"
                 class="fw-bold text-primary text-decoration-none">🦆 DuckTracker</a>
              <div class="text-muted small mt-1">Manage flocks, track stats, and monitor performance.</div>
            </div>
            <!-- Footer links (horizontal, subtle) -->
            <div class="col-md-6 text-center text-md-end">
              <ul class="list-inline mb-2 mb-md-1">
                <li class="list-inline-item">
                  <a href="{% url 'about' %}" class="text-muted text-decoration-none">About</a>
                </li>
                <li class="list-inline-item">
                  <a href="{% url 'ducks:flock-list' %}"
                     class="text-muted text-decoration-none">Flocks</a>
                </li>
                <li class="list-inline-item">
                  <a href="#" class="text-muted text-decoration-none">Privacy</a>
                </li>
              </ul>
              <div class="text-muted small">© {{ now|date:"Y" }} {{ SITE_NAME|default:"DuckTracker" }}</div>
            </div>
          </div>
        </div>
      </footer>
    {% endblock footer %}
    {% block modal %}
    {% endblock modal %}
    {% block loader %}
    {% endblock loader %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>

duck_tracker/duck_tracker/templates/form_field.html
{% if not field.is_hidden %}<label for="{{ field.id_for_label }}">{{ field.label }}:</label>{% endif %}
{% if field.field.widget.input_type == "date" %}
  <div class="date-input-wrapper" style="display: flex; gap: 8px; align-items: center;">
    {{ field }}
    <button type="button" class="btn-clear-date" style="background: none; border: none; cursor: pointer; padding: 4px; color: #666; font-size: 18px; flex-shrink: 0;" title="Clear date">✕</button>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      const inputId = "{{ field.id_for_label }}";
      const dateInput = document.getElementById(inputId);
      const clearBtn = dateInput?.parentElement.querySelector(".btn-clear-date");
      
      if (clearBtn && dateInput) {
        clearBtn.addEventListener("click", (e) => {
          e.preventDefault();
          e.stopPropagation();
          dateInput.value = "";
          dateInput.blur();
        });
      }
    });
  </script>
{% else %}
  {{ field }}
{% endif %}
{% if field.help_text %}<small>{{ field.help_text }}</small>{% endif %}